services:
  neo4j:
    image: neo4j:latest
    container_name: rolodex-neo4j
    ports:
      - "7474:7474"  # HTTP interface
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    environment:
      # Use the default password 'password' for user 'neo4j'
      # You can change this, but ensure it matches NEO4J_AUTH in .env if you do
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Required for newer versions

volumes:
  neo4j_data:
